on: [push, pull_request]

name: Default

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest

    services:
      wiremock:
        image: rodolpheche/wiremock
        ports: 
          - 8080:8080
        options: --name wiremock -v ${{ github.workspace }}/tests/stubs:/home/wiremock

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: 'checkout'

      - name: Move files
        run: sudo apt-get update && sudo apt-get install -y rsync && sudo rsync -avu checkout/ ./ && sudo chown -R 1001 .

      - name: Restart wiremock
        uses: docker://docker
        with:
          args: docker restart wiremock

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test 
          args: --features isahc,mercy,squirrel-girl,inertia,starfox,mock --target x86_64-unknown-linux-gnu
