name: Update
on:
  repository_dispatch:
    types:
      - octokit/openapi release
  workflow_dispatch:
    inputs:
      version:
        description: "Version of https://crates.io/crates/roctogen"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2

